### ISSUE TITLE
Proposal: Create a generic function/static method template spec/implementation

### ISSUE THREAD

**Issue by TysonAndre** [TysonAndre/phan#10]
This will improve analysis of some built in functions.

I don't see anything like this in other projects, and phan/other things only support it on instances.
In general, if it can be expressed by the below, there should be some equivalent for static methods or global functions (where T and U are template types or derived from template types) 

````
TemplateWrapper::__construct(T $param1, U $param2)`
and TemplateWrapper->someComputation() : DerivativeType<T, U>
```

---

Examples:

```
/**
 * @template T
 * @template U
 * @param callable $c
 * @param array $array
 * @return array
 * @staticTemplateParam function(T$x):U $c
 * @staticTemplateParam T[] $array
 * @staticTemplateReturn U[]
 */
function array_map(callable $c, array $values) : array {}
```

```
// More complicated than that, array_filter and array_map have options to also take the key.
/**
 * @template T
 * @template U
 * @param array $array
 * @param callable $filter
 * @return array
 * @staticTemplateParam T[] $x
 * @staticTemplateParam function(T$x):bool $filter
 * @staticTemplateReturn T[]
 */
function array_filter(array $values, callable $c) : array{}
```

```
/**
 * @template T
 * @param array &$array
 * @return mixed|false
 * @staticTemplateParam T[] &$x
 * @staticTemplateReturn T|false
 */
function array_pop(array &$x) {}
```

---

General guidelines for the @staticTemplateReturn

- Must be part of the provided parameters, or a return value of a provided parameter(if closures exist)
- If a closure is provided taking (only?) a template as a parameter, the parameter must be another parameter or a return value of a parameter
- Can convert to/from generic arrays: If T is provided, T[] can be returned. if T[] is provided, T can be returned
- Warn if provided value(s) don't match up with the corresponding templates
- Warn if the declaration doesn't match with the static template declaration
- TODO: what about optional parameters?

Obstacles:

- Return type of Closures aren't tracked - they just become a generic`Closure`.

**Comment by hworld** [comment]
Honestly, I think in my coding, generic functions would be more valuable than templated classes. From what I know in Phan, it's impossible to do something like: `get_last($arr)` and have it know that it'll return the T part of array<T>, yeah?

Has there been more discussion about something like this in the main Phan repository?

**Comment by TysonAndre** [comment]
No, there hasn't been discussion in the main Phan repository.

Src/Phan/Plugin/Internal/ contains a hardcoded implementation for end(), array_pop, array_values, etc.

So this task would be to allow doing that dynamically

**Comment by TysonAndre** [comment]
This repo contains random ideas, things that aren't fully thought out yet, etc

**Comment by TysonAndre** [comment]
Other notes: `@param T[]` would be more consistent with Phan's existing template implementation for classes, and cleaner.

That would just require adding templates to a function or method before interpreting other phpdoc tags.

`@phan-param` could be introduced in case of incompatibilities with other tools, etc. (E.g. T is an undefined class)

**Comment by hworld** [comment]
Yeah, that's what I was thinking too.

So it could either be:
```php
/**
 * @template T
 * @param T $array
 * @return T|false
 */
function array_pop(array $values) {}
```

But that may annoy other intellisense tools that wouldn't know what `\T` resolves to. So instead it could be an extension on top such as:
```php
/**
 * @template T
 * @param array $values
 * @phan-param T[] $values
 * @return mixed|false
 * @phan-return T|false
 */
function array_pop(array $values) {}
```

This would be extremely helpful (and could also get rid of the custom code written for PHP functions). I'll try to take a look at the code in Phan for doing the `array_*` methods to see how something like this may work within Phan.

**Comment by TysonAndre** [comment]
Moved the remaining work to https://github.com/phan/phan/issues/3238
